#!/usr/bin/with-contenv bash

if [ ! -f /config/.ssh/id_rsa ]
then
    mkdir -p /config/.ssh
    ssh-keygen -P '' -f /config/.ssh/id_rsa
    printf "StrictHostKeyChecking no\n" >> /etc/ssh/ssh_config
    #update the ssh config and set the pub/private keys
    sed -i 's+#   IdentityFile ~+IdentityFile /config+' /etc/ssh/ssh_config
    printf "GlobalKnownHostsFile /config/.ssh/known_hosts" >> /etc/ssh/ssh_config

    printf "Host *\n    ControlPath ~/.ssh/controlmasters/%%r@%%h:%%p\n    ControlMaster auto\n    ControlPersist 2h\n" > /config/.ssh/config
    mkdir -p /config/.ssh/controlmasters

    chown -R plex.plex /config/.ssh
    chmod 600 /config/.ssh/config /config/.ssh/id_rsa /config/.ssh/id_rsa.pub

    chown -R plex:plex /usr/lib/plexmediaserver
fi
