#!/usr/bin/with-contenv bash
if grep -q 'StrictHostKeyChecking no'  /etc/ssh/ssh_config;
then
    echo "ssh_config contains everything we need"
else
    printf "StrictHostKeyChecking no\n" >> /etc/ssh/ssh_config
    #update the ssh config and set the pub/private keys
    sed -i 's+#   IdentityFile ~+IdentityFile /config+' /etc/ssh/ssh_config
    #printf "IdentityFile /config/.ssh/identity
    ##IdentityFile /config/.ssh/id_rsa
    #IdentityFile /config/.ssh/id_dsa
    #IdentityFile /config/.ssh/id_ecdsa
    #IdentityFile /config/.ssh/id_ed25519
    printf "GlobalKnownHostsFile /config/.ssh/known_hosts\n" >> /etc/ssh/ssh_config
fi


