#!/usr/bin/with-contenv bash

if [ ! -f /etc/ssh/plex/authorized_keys ]
then
    mkdir -p /etc/ssh/plex

    if [ ! -f /config/.ssh/id_rsa.pub ]
    then
        echo "ERROR: public key file not found in /config/.ssh"
        exit 1
    else
        echo "INFO: importing public key" && \
        # import public key
        cat /config/.ssh/id_rsa.pub > /etc/ssh/plex/authorized_keys && \
        # enable plex user ssh login
        usermod -p '*' plex
    fi
else
    echo "INFO: Public key already loaded. Skipping..."
fi
